enum EQueryKeys {
  GET_SESSION_LIST = 'GET_SESSION_LIST',
  GET_EMPLOYEE_COLLECTION = 'GET_EMPLOYEE_COLLECTION',
  GET_KIT_COLLECTION = 'GET_KIT_COLLECTION',
  GET_LOCATION_COLLECTION = 'GET_LOCATION_COLLECTION',
  GET_SESSION = 'GET_SESSION',
}

export { EQueryKeys }
